version: '2'
services:
  # netmuxd:
  #    container_name: netmuxd
  #    build:
  #     context: .
  #     dockerfile: netmuxd.dockerfile
  #    command: sh -c "cargo build && cp target/debug/netmuxd /build/"
  #    volumes: 
  #     - ./bin:/build
  # anisette:
  #   build: ./anisette
  #   restart: unless-stopped
  #   ports:
  #     - "6969:6969"
  altserverhost:
    build: .
    container_name: altserverhost
    volumes:
      - '/dev/bus/usb:/dev/bus/usb'
      - '/var/lib/lockdown:/var/lib/lockdown'
      - '/var/run:/var/run'
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host
  altservermacvlan:
    build: .
    container_name: altservermacvlan
    volumes:
      - '/dev/bus/usb:/dev/bus/usb'
      - '/var/lib/lockdown:/var/lib/lockdown'
      - '/var/run:/var/run'
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    stdin_open: true
    tty: true
#    network_mode: host
    networks:
      macvlan:
        ipv4_address: 192.168.1.42
  altserveripvlan:
    build: .
    container_name: altservermacvlan
    volumes:
      - '/dev/bus/usb:/dev/bus/usb'
      - '/var/lib/lockdown:/var/lib/lockdown'
      - '/var/run:/var/run'
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    stdin_open: true
    tty: true
#    network_mode: host
    networks:
      ipvlan:
        ipv4_address: 192.168.1.42

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: wlan0 #your ethernet interface
    ipam:
      config:
        - subnet: 192.168.1.0/24
  ipvlan:
    driver: ipvlan
    driver_opts:
      ipvlan_mode: l2
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
