version: '3'
services:
  netmuxd:
     container_name: netmuxd
     build: 
      dockerfile: netmuxd.dockerfile
     command: sh -c "cargo build && cp target/debug/netmuxd /build/"
     volumes: 
      - ./bin:/build
  anisette:
    build: ./provision
    restart: unless-stopped
    ports:
      - "6969:6969"
