version: '2'
services:
  netmuxd:
     container_name: netmuxd
     build:
      context: .
      dockerfile: netmuxd.dockerfile
     command: sh -c "cargo build && cp target/debug/netmuxd /build/"
     volumes: 
      - .:/build

  altserver:
     container_name: altserver
     build:
      context: .
      dockerfile: altserver.dockerfile
     command: sh -c "mkdir build && make && cp /buildenv/altserver/AltServer-`arch` /build/altserver"
     volumes: 
      - .:/build
  
  config:
    build: .
    container_name: altserver_config
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /var/lib/lockdown:/var/lib/lockdown
      - /var/run:/var/run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - CONFIG=true

  daemon:
    build: .
    container_name: daemon
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - /var/lib/lockdown:/var/lib/lockdown
      - /var/run:/var/run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    network_mode: host
    restart: unless-stopped
