version: '3'
services:
  netmuxd:
     build: netmuxd_builder
     command: sh -c "cargo build && cp target/debug/netmuxd /build/"
     volumes: 
      - .:/build
  anisette:
    build: ./provision
    restart: unless-stopped
    ports:
      - "6969:6969"
