[package]
name = "netmuxd"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

default-run = "netmuxd"

[[bin]]
name = "test"
path = "src/test.rs"

[[bin]]
name = "passthrough"
path = "src/passthrough.rs"

[dependencies]
tokio = { version = "*", features = [ "full" ] }
futures-util = { version = "*" }

zeroconf = { version = "*" }
mdns = { version = "*" }

rusty_libimobiledevice = { version = "*", features = [ "static", "vendored" ] }
plist_plus = { version = "*", features = [ "static", "vendored" ] }

log = { version = "*" }
env_logger = { version = "*" }
colored = { version = "*" }

rusb = { version = "*" }
libusb1-sys = { version = "*" }
